image:
  file: .gitpod.DockerFile
tasks:
  - name: htop
    init: |
      pip install --upgrade pip
      pip install html2text
      pip install jq
      pip install ipython-sql~=0.5 --upgrade
      pip install sqlparse
      pip install SQLAlchemy --upgrade 
      pip install psycopg2-binary
      pip install pickleshare
      pip install pgspecial
      pip install pandas
      pip install mysql-connector-python
    command: |
      htop
  - name: ybu-lab
    init: |
      (
        set -e
        cp -r ${GITPOD_REPO_ROOT}/gitpod_conf/yugabyted.conf ${YB_PATH_BASE}/node1/yugabyted.conf
        cp -r ${GITPOD_REPO_ROOT}/gitpod_conf/yugabyted.conf ${YB_PATH_BASE}/node2/yugabyted.conf
        cp -r ${GITPOD_REPO_ROOT}/gitpod_conf/yugabyted.conf ${YB_PATH_BASE}/node3/yugabyted.conf
        echo "$(date) –  copied yugabyted.conf"
        chmod 777 ${GITPOD_REPO_ROOT}/start_all.sh
        chmod 777 ${GITPOD_REPO_ROOT}/stop_and_destroy_all.sh
      )
    command: |
      mysql -h 127.0.0.1 -u root < /workspace/YugabyteDB-Voyager/sakila-db/sakila-schema.sql
      mysql -h 127.0.0.1 -u root < /workspace/YugabyteDB-Voyager/sakila-db/sakila-data.sql
      cd ${GITPOD_REPO_ROOT}
      ./start_all.sh region
      gp open 01_Lab_Setup.ipynb
ports:
  - port: 3306
    onOpen: ignore
  - port: 3600
    onOpen: ignore
  - port: 5433
    onOpen: ignore
  - port: 7000
    onOpen: notify
  - port: 7100
    onOpen: ignore
  - port: 8200
    onOpen: notify
  - port: 9000-9040
    onOpen: ignore
  - port: 9042
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 12000
    onOpen: ignore
  - port: 13000
    onOpen: ignore
  - port: 15433
    onOpen: open-browser
  - port: 37843
    onOpen: ignore
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
